import {
  BiCaretUp,
  BiCaretDown,
  BiChevronUp,
  BiChevronDown,
  BiChevronRight,
  BiChevronLeft,
  BiCaretRight,
  BiCaretLeft,
  BiImageAdd,
  BiQr,
  BiQuestionMark,
  BiSearch,
  BiTimeFive,
  BiX,
  BiXCircle,
  BiBlock,
  BiCheck,
  BiCheckCircle,
  BiErrorCircle,
  BiInfoCircle,
  BiMinus,
  BiMinusCircle,
  BiTrash,
  BiFilterAlt,
  BiHelpCircle,
  BiDotsVertical,
  BiDownload,
  BiEdit,
  BiHistory,
  BiNote,
  BiMoon,
  BiSun,
  BiLayout,
  BiArchive,
  BiLogOut,
  BiPlus,
  BiZoomIn,
  BiZoomOut,
  BiMessageSquareDetail,
  BiMicrophone,
  BiFullscreen,
  BiCloudUpload,
  BiFolder,
  BiCookie,
  BiGitBranch,
  BiUser,
  BiDollar,
  BiSmile,
  BiCustomize,
  BiFolderOpen,
  BiServer,
  BiCategory,
  BiCast,
  BiPhone,
  BiDetail,
  BiCopy,
  BiFileBlank,
} from "react-icons/bi";

const Icons = {
  CaretTop: BiCaretUp,
  CaretRight: BiCaretRight,
  CaretDown: BiCaretDown,
  CaretLeft: BiCaretLeft,
  Copy: BiCopy,
  FileBlank: BiFileBlank,

  Smile: BiSmile,
  Server: BiServer,
  Category: BiCategory,
  Detail: BiDetail,
  Cast: BiCast,
  Phone: BiPhone,
  Dollar: BiDollar,
  User: BiUser,
  FolderOpen: BiFolderOpen,
  Customize: BiCustomize,

  ChevronTop: BiChevronUp,
  ChevronRight: BiChevronRight,
  ChevronBottom: BiChevronDown,
  ChevronLeft: BiChevronLeft,

  X: BiX,
  Doubt: BiQuestionMark,
  Check: BiCheck,
  Minus: BiMinus,

  XCircle: BiXCircle,
  DoubtCircle: BiHelpCircle,
  CheckCircle: BiCheckCircle,
  MinusCircle: BiMinusCircle,
  AlertCircle: BiErrorCircle,
  InfoCircle: BiInfoCircle,

  Layout: BiLayout,
  Search: BiSearch,
  Plus: BiPlus,
  ZoomIn: BiZoomIn,
  ZoomOut: BiZoomOut,
  Clock: BiTimeFive,
  History: BiHistory,
  Edit: BiEdit,
  Trash: BiTrash,
  Filter: BiFilterAlt,
  Note: BiNote,
  Moon: BiMoon,
  Sun: BiSun,
  MessageSquare: BiMessageSquareDetail,
  Microphone: BiMicrophone,
  Fullscreen: BiFullscreen,
  Branch: BiGitBranch,

  CloudUpload: BiCloudUpload,
  Folder: BiFolder,
  Cookie: BiCookie,

  Logout: BiLogOut,
  AddImage: BiImageAdd,
  DotsVertical: BiDotsVertical,
  Dowload: BiDownload,
  Block: BiBlock,
  QRCode: BiQr,
  Archive: BiArchive,
};

export { Icons };
