import {
  BiCaretUp,
  BiCaretDown,
  BiChevronUp,
  BiChevronDown,
  BiChevronRight,
  BiChevronLeft,
  BiCaretRight,
  BiCaretLeft,
  BiImageAdd,
  BiQr,
  BiQuestionMark,
  BiSearch,
  BiTimeFive,
  BiX,
  BiXCircle,
  BiBlock,
  BiCheck,
  BiCheckCircle,
  BiErrorCircle,
  BiInfoCircle,
  BiMinus,
  BiMinusCircle,
  BiTrash,
  BiFilterAlt,
  BiHelpCircle,
  BiDotsVertical,
  BiDownload,
  BiEdit,
  BiHistory,
  BiNote,
  BiMoon,
  BiSun,
  BiLayout,
  BiArchive,
  BiLogOut,
  BiPlus,
  BiZoomIn,
  BiZoomOut,
  BiMessageSquareDetail,
  BiMicrophone,
  BiFullscreen,
} from "react-icons/bi";

const Icons = {
  CaretTop: BiCaretUp,
  CaretRight: BiCaretRight,
  CaretDown: BiCaretDown,
  CaretLeft: BiCaretLeft,

  ChevronTop: BiChevronUp,
  ChevronRight: BiChevronRight,
  ChevronBottom: BiChevronDown,
  ChevronLeft: BiChevronLeft,

  X: BiX,
  Doubt: BiQuestionMark,
  Check: BiCheck,
  Minus: BiMinus,

  XCircle: BiXCircle,
  DoubtCircle: BiHelpCircle,
  CheckCircle: BiCheckCircle,
  MinusCircle: BiMinusCircle,
  AlertCircle: BiErrorCircle,
  InfoCircle: BiInfoCircle,

  Layout: BiLayout,
  Search: BiSearch,
  Plus: BiPlus,
  ZoomIn: BiZoomIn,
  ZoomOut: BiZoomOut,
  Clock: BiTimeFive,
  History: BiHistory,
  Edit: BiEdit,
  Trash: BiTrash,
  Filter: BiFilterAlt,
  Note: BiNote,
  Moon: BiMoon,
  Sun: BiSun,
  MessageSquare: BiMessageSquareDetail,
  Microphone: BiMicrophone,
  Fullscreen: BiFullscreen,

  Logout: BiLogOut,
  AddImage: BiImageAdd,
  DotsVertical: BiDotsVertical,
  Dowload: BiDownload,
  Block: BiBlock,
  QRCode: BiQr,
  Archive: BiArchive,
};

export { Icons };
